CREATE TABLE tiendas (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "nombre" varchar(255) NOT NULL,
  CONSTRAINT "tienda_pk" PRIMARY KEY ("id")
)
;

CREATE TABLE productos (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "imgSrc" varchar(500),
  "dataOriginal" varchar(500),
  "imgTitle" varchar(255) NOT NULL,
  "priceDolar" varchar(100) NOT NULL,
  "priceSoles" varchar(100) NOT NULL,
  "url" varchar(500) NOT NULL,
  "tiendas_id" int4 NOT NULL,
  CONSTRAINT "producto_pk" PRIMARY KEY ("id")
)
;

ALTER TABLE productos ADD CONSTRAINT "fk_productos_tiendas" FOREIGN KEY ("tiendas_id") REFERENCES tiendas ("id");

INSERT INTO tiendas (nombre) VALUES('Importaciones Impacto');
INSERT INTO tiendas (nombre) VALUES('C&C Computer');
INSERT INTO tiendas (nombre) VALUES(' Corporación Sercoplus SAC.');

select * from tiendas
select * from productos
